"use client";

import Link from "next/link";
import { CalendarRange, PackageSearch } from "lucide-react";
import { useEffect, useState } from "react";
import { getOrders, type RentalOrder } from "@/features/customer/api";
import { Panel } from "@/components/admin/Panel";
const money = (v: string) => new Intl.NumberFormat("en-IN", {style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(v));
export default function OrdersPage() { const [orders, setOrders] = useState<RentalOrder[]>([]); const [loading, setLoading] = useState(true); useEffect(()=>{getOrders().then(d=>setOrders(d.rentalOrders ?? d.orders ?? [])).finally(()=>setLoading(false));},[]); return <div><div className="mb-8"><p className="mb-2 text-xs font-bold uppercase tracking-[.18em] text-accent">Rental history</p><h1 className="font-display text-3xl font-bold text-text sm:text-4xl">My bookings</h1><p className="mt-2 text-sm text-chalk">Track your booking requests, pickups, and completed rentals.</p></div><Panel className="overflow-hidden">{loading ? <div className="p-10 text-center text-chalk">Loading bookings…</div> : orders.length === 0 ? <div className="p-12 text-center"><PackageSearch className="mx-auto text-accent" size={32}/><p className="mt-4 font-semibold text-text">Your booking history is empty.</p><Link className="mt-3 inline-block text-sm font-bold text-accent" href="/dashboard/catalog">Browse available rentals</Link></div> : <div className="divide-y divide-border">{orders.map(order => <div key={order.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><div className="rounded-xl bg-accent/15 p-3 text-accent"><CalendarRange size={20}/></div><div><p className="font-display font-bold text-text">{order.items.map(i=>i.product.name).join(", ")}</p><p className="mt-1 text-sm text-chalk">{order.rentalNumber} · {new Date(order.rentalStart).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"})} – {new Date(order.rentalEnd).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"})}</p><p className="mt-1 text-xs text-chalk">{order.vendor?.companyName ?? order.vendor?.fullName ?? "Rental partner"}</p></div></div><div className="sm:text-right"><p className="font-bold text-text">{money(order.grandTotal)}</p><div className="mt-1 flex gap-2 sm:justify-end"><span className="rounded-full bg-accent/15 px-2 py-1 text-[11px] font-bold text-accent">{order.status.replace("_", " ")}</span><span className="rounded-full bg-black/5 px-2 py-1 text-[11px] font-bold text-chalk dark:bg-white/10">{order.paymentStatus.replace("_", " ")}</span></div></div></div>)}</div>}</Panel></div>; }
